letitgo:
  name: sdf
  description: sdf for the lazy developer
  actions:
    - type: changelog
      file: CHANGELOG.md

    - type: archive
      source: "./build/bin/*"
      target: "./build/pkg/"
      extras:
        - "LICENSE"
        - "CHANGELOG.md"

    - type: githubrelease
      assets:
        - ./build/pkg/*

    - type: homebrew
      homepage: https://github.com/NoUseFreak/sdf
      url: https://github.com/NoUseFreak/sdf/releases/download/{{ .Version }}/darwin_amd64.zip
      version: "{{ .Version }}"
      tap:
        url: git@github.com:NoUseFreak/homebrew-brew.git
      test: system "#{bin}/{{ .Name }} -h"

    - type: gofish
      githubusername: NoUseFreak
      homepage: https://github.com/NoUseFreak/sdf
      artifacts:
        - os: darwin
          arch: amd64
          url: https://github.com/NoUseFreak/sdf/releases/download/{{ .Version }}/darwin_amd64.zip
        - os: linux
          arch: amd64
          url: https://github.com/NoUseFreak/sdf/releases/download/{{ .Version }}/linux_amd64.zip
        - os: windows
          arch: amd64
          url: https://github.com/NoUseFreak/sdf/releases/download/{{ .Version }}/windows_amd64.zip
