[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.11.0"

[[constraint]]
  name = "github.com/logrusorgru/aurora"
  version = "2.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/sahilm/fuzzy"
  version = "0.1.0"
